# Generated by Django 5.2.5 on 2025-09-03 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("charge_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Charges",
            new_name="Charge",
        ),
    ]
